"""init business cleaning schema

Revision ID: 3d93048e2663
Revises:
Create Date: 2026-07-21 17:33:17.612074

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as psql

# revision identifiers, used by Alembic.
revision: str = "3d93048e2663"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


appointment_status = psql.ENUM(
    "SUBMITTED",
    "COMPLETED",
    "IN_PROGRESS",
    "ASSIGNED",
    "CANCELLED",
    name="appointmentstatus",
    create_type=False,
)


roles = psql.ENUM(
    "USER", "CLEANER", "ADMIN", "MANAGER", "CUSTOMER", name="roles", create_type=False
)

apartment_size = psql.ENUM(
    "LARGE", "SMALL", "MEDIUM", name="apartmentsize", create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    roles.create(bind, checkfirst=True)
    appointment_status.create(bind, checkfirst=True)
    apartment_size.create(bind=bind, checkfirst=True)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False, unique=True),
        sa.Column("_hash_password", sa.String(), nullable=False),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updatedAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "role",
            roles,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "appointments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cleaner_id", sa.Integer(), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            appointment_status,
            nullable=False,
        ),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("hours", sa.Integer(), nullable=False),
        sa.Column("is_recurred", sa.Boolean(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("apartment_size", apartment_size, nullable=False),
        sa.Column("paid_amount_cents", sa.Integer(), nullable=True),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updatedAt", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cleaner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("appointments")
    op.drop_table("users")
    bind = op.get_bind()
    appointment_status.drop(bind, checkfirst=True)
    roles.drop(bind, checkfirst=True)
    apartment_size.drop(bind=bind, checkfirst=True)
    # ### end Alembic commands ###
